root=$(git rev-parse --show-toplevel)
makefile=$root/Makefile
marker="# start autogenerated section"

tmp="$(mktemp)"

# copy everything above the marker
awk "/${marker}/{exit}1" "$makefile" > "$tmp"

# append the new section
{
    echo "$marker"
    echo '# do not edit below, auto generated via: `clang/gcc -MM ./source/*.c -I ./headers/`'
    echo
    cc -MM $root/source/*.c -I $root/headers/ | sed "s|$root/||g"
    echo
    echo '# do not edit above, auto generated via: `clang/gcc -MM ./source/*.c -I ./headers/`'
} >> "$tmp"

mv "$tmp" "$makefile"